### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by iamdylanngo** [techdivision/import-sample-data#2]
How to use it?
I don't see any more documents to run it?
Please give me documentation?

**Comment by wagnert** [comment]
Hi @dylanngo95, please have a look at our Pacemaker website under https://pacemaker.techdivision.com/ for further product information, as well as the documentation for the community edition https://docs.met.tdintern.de/pacemaker/1.3/ce_usage.html :-) Additionally we've a Slack Community Channel under https://join.slack.com/t/pacemaker-for-magento/shared_invite/zt-f9158omo-3vMOxwW8rvESX3elxfZzpg you're very welcome if you have any further questions. Thanks for your interest in Pacemaker :-)
